### ISSUE TITLE
! دی ماه همه ی سالها 30 روزه اند

### ISSUE THREAD

**Issue by bug-tracker** [farhadi/JalaliJSCalendar#11]
نیازی به روشنگری ندارد. تنها با آزمودن پرونده ی جلالی در پوشه ی مثالها می توان اینرا دید.

**Comment by rkeshmir** [comment]
یعنی دی ماه بعضی سال‌ها باید ۲۹ روزه باشد؟ منظورتون اسفنده؟

**Comment by bug-tracker** [comment]
بله، معذرت میخوام. راستش تقویمهای بسیاری را بررسی کردم (از ساخت بچه های ایرانی تا خارجی) و همه ی اونها دکمه ی ماه و سال بعد را مخالف جایی که شما گذاشته اید گذاشته بودند. این بود که مغز من بیچاره هم روی همین نکته قفل شده و با زدن دکمه ی دست راست به این گمان که دارم میرم به اسفند، بیهوا 30 روزه دیدن دی ماه را اسفند ماه تلقی کرده و با اینکه توی عنوان هم نوشته بودم دی ولی منظورم اسفند بود. باری، تقویم شما درست است و اشکالی ندارد. تنها عادتهاست که کار دست ما می دهد.
خوش باش.
